# No consigo que funcione con docker-compose porque tengo que utilizar network=host. Pongo el comando docker. El servicio corre por el puerto 8080

docker run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 --name open-webui --restart always ghcr.io/open-webui/open-webui:main
