version: '3.3'

services:

  wordpress:
    image: wordpress:latest
    container_name: wp1 #Cambiar si se quiere tener varias instancias
    hostname: wordpress
    restart: unless-stopped
    ports:
      - "61000:80" #Cambiar puerto externo si procede
    environment:
      WORDPRESS_DB_HOST: db:3306 #El puerto de la DB es interno, por lo que puede permanecer
      WORDPRESS_DB_USER: useradmin #Cambiar
      WORDPRESS_DB_PASSWORD: p4ssw0rd #Cambiar
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html #No dejar rutas relativas externas. Mejor hardcodear a una carpeta que esté en el home
    networks:
      - red_wp1 #Cambiar. Coherencia con el nombre del container

  db:
    image: mariadb:latest
    container_name: db_wp1 #Cambiar. Coherencia con el nombre del container
    hostname: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd #Cambiar
      MYSQL_DATABASE: wordpress
      MYSQL_USER: useradmin #Cambiar
      MYSQL_PASSWORD: p4ssw0rd #Cambiar
    volumes:
      - ./db:/var/lib/mysql #No dejar rutas relativas externas. Mejor hardcodear a una carpeta que esté en el home
    networks:
      - red_wp1 #Misma red que el container de wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_wp1 #Cambiar. Coherencia con el nombre del container
    restart: unless-stopped
    ports:
      - "60000:80" #Cambiar puerto externo si procede
    depends_on:
      - db
    environment:
      PMA_HOST: db:3306 #El puerto de la DB es interno, por lo que puede permanecer
      MYSQL_ROOT_PASSWORD: p4ssw0rd #Cambiar
      PMA_USER: useradmin #Cambiar
      PMA_PASSWORD: p4ssw0rd #Cambiar
    networks:
      - red_wp1 #Misma red que el container de wordpress

networks:
  red_wp1: #Misma red que el container de wordpress. Solo cambiar el nombre, no hay que rellenar nada.
